FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow scikit-learn pandas cloudpickle

COPY . /app

EXPOSE 5002

CMD ["sh", "-c", "mlflow models serve -m mlruns/1/$(ls -t mlruns/1 | head -n 1)/artifacts/model_pipeline --host 0.0.0.0 --port 5002 --no-conda"]