services:
  fastapi_app:
    build:
      context: .
      dockerfile: backend/Dockerfile.api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_URL=http://mlflow_serve:5002/invocations
      - MLFLOW_TRACKING_URI=http://mlflow_ui:5000
    depends_on:
      - mlflow_serve
      - mlflow_ui
    restart: always

  mlflow_serve:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_serve
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
      - MLFLOW_EXPERIMENT_NAME=bank_marketing_bandit_docker
    restart: always

  mlflow_ui:
    image: python:3.11-slim
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install mlflow && mlflow server --backend-store-uri sqlite:////app/mlflow.db --default-artifact-root /app/mlruns --host 0.0.0.0 --port 5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_app
    ports:
      - "8050:80"
    depends_on:
      - fastapi_app
    restart: always
