services:
  fastapi_app:
    build:
      context: .
      dockerfile: backend/Dockerfile.api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:${PWD}
    working_dir: ${PWD}
    environment:
      - MLFLOW_URL=http://mlflow_serve:5002/invocations
      - MLFLOW_TRACKING_URI=sqlite:///${PWD}/mlflow.db
    depends_on:
      - mlflow_serve
    restart: always

  mlflow_serve:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_serve
    ports:
      - "5002:5002"
    volumes:
      - .:${PWD}
    working_dir: ${PWD}
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///${PWD}/mlflow.db
    restart: always

  mlflow_ui:
    image: python:3.11-slim
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - .:${PWD}
    working_dir: ${PWD}
    command: >
      sh -c "pip install mlflow && mlflow ui --backend-store-uri sqlite:///${PWD}/mlflow.db --host 0.0.0.0 --port 5000"
    restart: always