FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    cloudpickle \
    matplotlib \
    mlflow \
    pandas \
    psutil \
    pyarrow \
    scikit-learn

COPY . /app
RUN sed -i 's/\r$//' /app/docker/mlflow-entrypoint.sh

EXPOSE 5002

CMD ["sh", "/app/docker/mlflow-entrypoint.sh"]
