FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow scikit-learn pandas cloudpickle

COPY . /app

EXPOSE 5002

CMD ["mlflow", "models", "serve", "-m", "models:/bank_marketing_model/latest", "--host", "0.0.0.0", "--port", "5002", "--env-manager", "local"]
