FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

COPY . /app
RUN sed -i 's/\r$//' /app/docker/api-entrypoint.sh

# Ajustado para apontar para o novo caminho dentro de backend/api
CMD ["sh", "/app/docker/api-entrypoint.sh"]
